### ISSUE TITLE
Question re: Manipulating log messages using middleware

### ISSUE THREAD

**Issue by scstarkey** [ptaoussanis/timbre#207] opened 2016-12-06 17:31 UTC
Greetings,

Not being familiar with this particular logging library, I'm unclear on how to manipulate log messages. I'm attempting to stamp request IDs onto all log messages for a particular thread with the following function and macro:

    (defn prepend-thread-id [data]
      (let [{:keys [?msg-fmt vargs]} data)]
        (assoc data :vargs (into [*thread-id*] vargs)
                    :?msg-fmt (str "[%s] " ?msg-fmt))))

    (defmacro with-thread-context [& body]
      `(binding [*thread-id* (slug/random-slug)]
         (log/with-merged-config {:middleware [prepend-thread-id]}
                                 ~@body)))

I can see the middleware being called, but the resulting log output seems to be unchanged. Am I manipulating the wrong things? What is a better way to go about this?

Is it better to set up a custom log format and context? Thing is I may or may not have a thread-id stamped, so I only want to update the message conditionally.

Thanks so much for your help!

All the best,

Stephen.

**Comment by ryfow** [comment] 2016-12-07 16:03
I'm also interested in an answer to this from @ptaoussanis.

In the mean time, I do know that you can change `:msg_` as I did here: https://github.com/ptaoussanis/timbre/pull/200#issuecomment-259541170

As I say in the comment, I don't know if it's a good idea or not.

**Comment by ptaoussanis** [comment] 2016-12-17 13:29
Hi there, the confusion re: changes to `vargs` not affecting output is being caused by a bug. Will fix and get back to you both.

**Comment by ptaoussanis** [comment] 2016-12-17 15:30
@scstarkey Hi Stephen,

Depending on your requirements, you may find that `timbre/with-context` does what you're looking for.

@scstarkey, @ryfow 

The confusion was due to a bug. When middleware modify `:vargs`, it _should_ automatically influence the values of `:msg_` and `:output_`. This'll be fixed in the next Timbre release.

Thanks for the report, and sorry for the trouble (and long delay fixing)!

**Comment by ptaoussanis** [comment] 2016-12-17 15:31
After the fix:

```clojure
(with-config
  {:level :debug
   :middleware [(fn [data] (assoc data :vargs ["qux"]))]
   :appenders
   {:println
    {:enabled? true
     :fn (fn [data] (println (force (:output_ data))))}}}

  (info "foo" "bar"))

;; %> 16-12-17 15:30:59 INFO [taoensso.timbre:288] - qux
```

**Comment by scstarkey** [comment] 2016-12-17 23:12
Thank you!

Stephen Starkey, ACC, CSP, CSM, CHP
empathy | connectedness | restorative | relator | belief
847-846-1786

**Comment by scstarkey** [comment] 2016-12-20 14:58
So I tried the latest code and noticed I can influence `vargs` but I can't influence `?msg-fmt` -- is this expected? How can I change the format?

**Comment by scstarkey** [comment] 2016-12-20 15:39
@ptaoussanis FYI this is the code I am using to stamp log messages with a randomly generated thread ID. The case where the `?msg-fmt` is null seems to work fine, but when it isn't, it seems to ignore the new `?msg-fmt`:

<pre>
(defn add-thread-id [thread-id {:keys [?msg-fmt]
                                [first-varg] :vargs
                                :as data}]
  (let [add-thread-id (partial str "[tid=" thread-id "] ")]
    (if ?msg-fmt
      (assoc data :?msg-fmt (add-thread-id ?msg-fmt))
      (assoc data :vargs [(add-thread-id first-varg)]))))

(defmacro with-thread-id [thread-id & body]
  `(log/with-merged-config {:middleware [(partial add-thread-id ~thread-id)]}
     ~@body))

(defmacro with-new-thread-id [bindings & body]
  `(let [~(first bindings) (slug/random-slug)]
     (with-thread-id ~(first bindings) ~@body)))
</pre>

**Comment by ptaoussanis** [comment] 2016-12-22 10:57
> So, @ptaoussanis, thanks for your effort to make this work! I tried the latest code and noticed I can influence vargs but I can't influence ?msg-fmt -- is this expected? How can I change the format?

Hi @scstarkey,

Yes, that's currently expected (`?msg-fmt` being read-only). Could you describe your use-case a little more so that I understand the motivation to rewrite the message pattern? Didn't realise that's something someone might want to do.

Is there a reason (say), you don't just prepend/append the thread identifier to the `:msg_` string, or adjust your output-fn to include the thread identifier?

**Comment by scstarkey** [comment] 2016-12-22 13:12
I guess I made a few assumptions:

1. Middleware is for manipulating the data of the log statement, and
2. Output-fn is for manipulating the style in which it gets output (changing colors, etc)

It seemed much more elegant to transform the data instead of hacking the output. Also, `:msg_` didn't seem to be available in the data map (which would make sense since middleware seems to be applied before the message is fully constructed).

I will follow your advice and use output-fn. However, it seems middlewares are quite stunted if they can only manipulate vargs -- what if you want to do something like PII scrubbing (which seems like a thing middleware was designed for) and someone logs a message ignorantly putting PII in the format instead of the vargs?

May I ask: what is their purpose if not to manipulate the data of the message, which includes its format?

**Comment by ptaoussanis** [comment] 2016-12-23 12:23
Thanks for the clear response-

> It seemed much more elegant to transform the data instead of hacking the output.

On the fence about this; one could make a reasonable argument that just constructing an appropriate output may be simpler (in the sense of fewer indirect dependencies between what you're doing and the final intended outcome).

Anyway, don't feel strongly about this; think it may be six of one.

> Also, :msg_ didn't seem to be available in the data map (which would make sense since middleware seems to be applied before the message is fully constructed).

Indeed, my mistake - sorry.

> However, it seems middlewares are quite stunted if they can only manipulate vargs --

They can modify (and use) any data flowing through, the question in this case is about timing dependencies for values that are automatically constructed (e.g. `:msg_`).

So why no support for a modification to `:?msg-fmt` influencing `:msg_`? Just never thought anyone would have a use case for doing so :-) Not against adding support, will take a look at refactoring all this when I'm in the code again next.

> and someone logs a message ignorantly putting PII in the format instead of the vargs?

Thanks for the example use case. TBH my first inclination would be to interpret this as programmer error? The intention behind middleware is (mostly) to deal with (variable) arguments provided by the user/environment. I.e. unpredictable data, where it might make sense to incur the cost and complexity of supporting arbitrary data transformation.

In this case we're talking about a fixed argument provided by the programmer.

To be clear: not against adding support anyway (if only to have everything behave in a consistent/predictable way), just explaining why it hadn't occurred to me earlier that someone might like the particular facility :-)

**Comment by scstarkey** [comment] 2016-12-23 13:19
Thanks for the thoughtful response and care! I see your point as well, and would have been happy with switching to and output-fn had you gone the other way. :-)

As it is, I will eagerly await the refactoring!

**Comment by ptaoussanis** [comment] 2017-04-15 10:40
Closing to focus on #211

**Closed by ptaoussanis** 2017-04-15 10:40 UTC
Labels: can close?
