### ISSUE TITLE
compile exception with 4.2.0

### ISSUE THREAD

**Issue by nicferrier** [ptaoussanis/timbre#146] opened 2015-12-31 10:09 UTC
```
<CompilerException java.lang.IllegalArgumentException: More than one matching method found: submit, compiling:(taoensso/timbre.clj:568:16)>
```

which means here: https://github.com/ptaoussanis/timbre/blob/master/src/taoensso/timbre.cljx#L568

I've no idea why this would show as a problem. Seems weird?

**Comment by ptaoussanis** [comment] 2015-12-31 10:16
Hi Nic, please provide further details?

How are you compiling? What version of Clojure are you using? What JVM version? Any particular behaviour triggering this?

Thanks

**Comment by nicferrier** [comment] 2015-12-31 11:15
Clojure 1.6.0 on Java HotSpot(TM) Client VM 1.8.0_25-b18

I'm just using: lein repl on a project for which timbre 3 was working fine. When the repl comes up I get this error, obviously as part of it bringing in the deps?

**Comment by ptaoussanis** [comment] 2016-01-03 03:59
Hi Nic,

I haven't been able to reproduce this on my end. As a random idea, trying one [change](https://github.com/ptaoussanis/timbre/commit/d4642dced1053e3884d32b6b284d48a9d8ec9c22) that might help.

Please confirm if that fixes the issue on your end? Otherwise you may need you to provide a reproducible repo that I can look at.

**Note**: tried to upload the change to Clojars but looks like they're still down due to the Linode DDoS attack. You'll unfortunately need to use a local Timbre copy:

1. `git clone https://github.com/ptaoussanis/timbre.git`
2. `git checkout dev`
3. Mod the `project.clj` version to something like `4.2.1-SNAPSHOT`
4. `lein build-once` to build your custom version of Timbre
5. `lein install` to install it to your local Maven repo
6. Include the same version string in your project's dependencies

Thanks again for the report

**Comment by nicferrier** [comment] 2016-01-03 12:54
Well, it occurs to me that maybe I didn't get a download because of the DDoS. I didn't notice any error like that. So I'll try this next week and maybe they'll be ok then.

**Comment by rdanitz** [comment] 2016-01-07 11:17
I got the same error although 4.2.0 worked for me before.
I could fix it by upgrading from clojure 1.6.0 to 1.7.0, everything else being the same.

**Comment by ptaoussanis** [comment] 2016-01-07 14:12
@rdanitz Hi Robert, could you please clarify: 4.2.0 worked for you before what?

**Comment by ptaoussanis** [comment] 2016-01-07 15:17
@rdanitz Oh, also- any chance you could possibly confirm whether `[com.taoensso/timbre "4.2.1-SNAPSHOT"]` solves the problem for you with Clojure 1.6? (The snapshot is now up on Clojars)

Thanks!

**Comment by rdanitz** [comment] 2016-01-08 12:22
@ptaoussanis 4.2.1-SNAPSHOT works with clojure 1.6.0 now.
Sorry for the confusion, I only checked 4.2.0 with clojure 1.7.0 before. My remark was regarding clojure 1.7.0.

**Comment by ptaoussanis** [comment] 2016-01-09 12:03
@rdanitz Awesome, thanks for confirming!

**Comment by ptaoussanis** [comment] 2016-01-14 05:27
Closing this with the release of https://github.com/ptaoussanis/timbre/releases/tag/v4.2.1

**Closed by ptaoussanis** 2016-01-14 05:27 UTC
Labels: bug?
