### ISSUE TITLE
problem with ns-whitelist

### ISSUE THREAD

**Issue by ghaskins** [ptaoussanis/timbre#280] opened 2019-03-21 16:26 UTC
Hi,  Timbre is awesome.  Thank you for providing it.

I am banging my head on the wall on a behavior of ns-whitelist I can't quite figure out.

I am generally able to whitelist my own namespaces and things behave as I would expect.  However, I am unable to whitelist [Pedestal](http://pedestal.io/).

For example, a log entry like:

```
19-03-21 16:12:54 Gregs-MacBook-Pro.local DEBUG [io.pedestal.interceptor.chain:75] - {:in end, :execution-id 22, :context-keys (:request :io.pedestal.interceptor.chain/execution-id :io.pedestal.interceptor.chain/stack :route :url-for :bindings :response), :line 321}
```
I can see the log output if I have no whitelist specified, but I am unable to specify _just_ the pedestal output.  I have tried a bunch of things like ```["io.pedestal.*"]``` but it always ends up filtering the pedestal output out.  I am able to use similar techniques with other namespaces and it works fine.  I don't understand what I am doing wrong.  Any guidance appreciated.

-Greg

**Comment by ptaoussanis** [comment] 2020-09-09 06:47
@ghaskins Hi Gregory, is this still an issue?

Is Pedestal actually using Timbre? If it's not, then your whitelist config won't have any effect one way or another since its logging calls won't be going through Timbre.

Beyond that, nothing obvious comes to mind to check.

If Pedestal is using Timbre and the whitelist still isn't working, a small reproducible example might help!

Thanks,

**Comment by ptaoussanis** [comment] 2020-09-09 08:48
Closing for now as part of issue triage, please feel free to reopen if this is still relevant!

**Closed by ptaoussanis** 2020-09-09 08:48 UTC
Labels: can close?, question/usage
