### ISSUE TITLE
Invalid :refer, var taoensso.encore/have does not exist

### ISSUE THREAD

**Issue by BorisKourt** [ptaoussanis/timbre#364] opened 2022-12-06 10:05 UTC
```clj
[:app] Compiling ...
------ ERROR -------------------------------------------------------------------
 File: jar:file:/Users/<~>/.m2/repository/com/taoensso/timbre/6.0.2/timbre-6.0.2.jar!/taoensso/timbre/appenders/core.cljc:1:1
--------------------------------------------------------------------------------

   1 | (ns taoensso.timbre.appenders.core
-------^------------------------------------------------------------------------
Invalid :refer, var taoensso.encore/have does not exist
--------------------------------------------------------------------------------
   2 |   "Core Timbre appenders without any special dependency requirements.
   3 |   These can be aliased into the main Timbre ns for convenience."
   4 |   {:author "Peter Taoussanis (@ptaoussanis)"}
   5 |   (:require
--------------------------------------------------------------------------------
```

When compiling for production with shadow-cljs I get this error from the last few versions of Timbre.

Version 5.2.1 is working fine. 

I have not been able to pinpoint an exact place in the changelog that starts to have this issue. But I guess it is related to the shuffling of community appenders? 

Thanks for any suggestions!

**Comment by ptaoussanis** [comment] 2022-12-06 10:21
@BorisKourt Hi Boris, apologies for the trouble!

It looks like you need to update your version of Encore.
I've just pushed `[com.taoensso/timbre "6.0.3"]` to Clojars, which includes a newer bundled version of Encore.

That should solve your problem, just make sure to run `lein clean` (or equivalent) to clear out any old build artifacts.

**Comment by ptaoussanis** [comment] 2022-12-06 10:51
@BorisKourt Is there a chance something else is bringing in an older version of Encore?
Please try check for encore in the output of `lein deps :tree` or equivalent.

I'm not too familiar with shadow-cljs, but this appears to be an identical issue to https://github.com/ptaoussanis/encore/issues/64, which should have hopefully been resolved with Encore `[com.taoensso/encore "3.37.1"]` and later.

If you can confirm that you really have the latest Encore and are seeing the issue, could you please try with [com.taoensso/encore "3.37.1"] precisely? If that's working, but later versions are not - it would seem to indicate that I inadvertently broke shadow-cljs support again.

In that case, I'll try get it running locally so that I can debug properly.

Thanks, and again sorry for the trouble!

**Comment by BorisKourt** [comment] 2022-12-06 11:05
Hey I checked using `deps :tree`, there were no references to older encore that I could search for. I double checked my excludes and made sure that my manual encore include should be the main one referenced. 

I then downgraded to `3.37.1` but am unable to test if that solved this issue due to:

```clj
Syntax error macroexpanding at (timbre.cljc:15:1).
Execution error (ExceptionInfo) at taoensso.encore/assert-min-encore-version (encore.cljc:1499).
Insufficient `com.taoensso/encore` version, you may have a dependency conflict: see http://goo.gl/qBbLvC for solutions.
```

I am not sure which version of timbre to downgrade to to fix this. Since if I go far enough back the original issue can go away. 

Thanks for taking the time!

**Comment by BorisKourt** [comment] 2022-12-06 12:03
Hey, this is working with this snapshot.

**Comment by ptaoussanis** [comment] 2022-12-06 12:16
Okay, great- thanks for the confirmation 👍 
That means that I must have somehow broken shadow support again after 3.37.1.

Will try get setup with shadow so I can debug properly myself, after which I'll push new versions of Encore and Timbre.
Might be a couple days.

In the meantime, I believe that the following combination should work:

```clojure
[com.taoensso/encore "3.37.1"]
[com.taoensso/timbre "6.0.2"]
```

Again, sorry about the nuisance.
Thanks a lot for reporting this, and for all the assistance debugging.

**Comment by BorisKourt** [comment] 2022-12-06 12:20
Thank you very much! I will keep an eye out for new versions.

**Comment by ptaoussanis** [comment] 2022-12-06 13:40
@BorisKourt I'm having some trouble reproducing the problem. 
I've not used `shadow-cljs` before, so it's very possible I'm making a mistake somewhere.

Here's the minimal project I'm using: https://github.com/ptaoussanis/temp-timbre-364

`shadow-cljs.edn` contains:

```clojure
 :dependencies
 [[com.taoensso/encore "3.42.0"]
  [com.taoensso/timbre  "6.0.3"]]
```

The init ns contents:

```clojure
(ns foo
  (:require
   [taoensso.encore :as enc]
   [taoensso.timbre :as timbre]
   [taoensso.timbre.appenders.core]
   ))

(defn init []
  (js/alert    (enc/have string? "hello 1"))
  (timbre/info (enc/have string? "hello 2"))
  )
```

I'm then running:
```bash
npx shadow-cljs browser-repl
npx shadow-cljs watch frontend
```

and opening `http://localhost:8080` in a browser.
So far, I'm not seeing any obvious compilation issues - and Timbre does seem to be operating normally.

Is there something in particular I need to do to trigger the error?
Do you see errors with my [example project](https://github.com/ptaoussanis/temp-timbre-364)?

**Comment by ptaoussanis** [comment] 2022-12-06 13:56
Update: can confirm that my example project _does_ confirm the problem with `[com.taoensso/encore "3.36.0"]`, but `[com.taoensso/encore "3.37.1"]` or newer _appears_ fine from what I can tell.

**Comment by BorisKourt** [comment] 2022-12-06 14:56
I will try to create my own repro. I am using shadow via lein, directly from the luminus +shadow template. Though it has now been many months in development, so a lot going on in here.

Regarding the second comment:

As far as I know I have cleared all cached output. It seems like its all in `target` and that gets completely wiped on `lein clean` I am not sure if shadow does any additional cache work. If it was the persistent wouldn't it still break with `[com.taoensso/encore "3.37.1-SNAPSHOT"]`?

**Comment by ptaoussanis** [comment] 2022-12-06 15:12
Not sure about luminus + shadow template, not familiar with either of those. But at least with the vanilla shadow-cljs, it seems to generate js files in the `public` dir by default.

> If it was the persistent wouldn't it still break with [com.taoensso/encore "3.37.1-SNAPSHOT"]?

I would definitely think so, yes. But not sure why I can't reproduce on my side. Weird things can definitely occur if stale build artifacts are somehow lingering. If it's non-trivial for you to try create your own repro (which I can totally understand), I'd maybe recommend starting with [my example project](https://github.com/ptaoussanis/temp-timbre-364) - just to rule out the possibility that you're seeing different results even with that.

What version of Cljs, and what compiler options are you using for your own project that's exhibiting the problem? Is this an `:advanced` compile?

**Comment by BorisKourt** [comment] 2022-12-06 15:14
Quick answer first before I dig in further, this is an `:advanced` production compile. The original issue only happens in the production build, I mention that but should have been more clear about the CLJS settings.

**Comment by ptaoussanis** [comment] 2022-12-06 15:27
Thanks for clarifying 👍 

Just tried `npx shadow-cljs release` on the [example project](https://github.com/ptaoussanis/temp-timbre-364), and that seems to build okay using `:advanced` mode from what I can tell.

Will continue investigating so long.

**Comment by BorisKourt** [comment] 2022-12-06 16:53
Just an update. I tried creating a new Luminus app with +shadow-cljs and adding timbre and encore. After doing a bunch of permutations of versions and settings I couldn't reproduce the issue.

Sadly going back to the original project and trying with anything but the snapshot you provided I am still getting the error. I am trying to figure out what the main differences are between this existing project and a fresh Luminus setup. But I am assuming that its something on my end and not yours.

**Comment by ptaoussanis** [comment] 2022-12-06 17:00
Thanks for keeping me updated 👍 

My best guess would still be that there's stale build artifacts squirrelled away somewhere. I'd try search in your base project dir for any .js files - might turn up an unexpected cache dir?

**Comment by ptaoussanis** [comment] 2022-12-07 07:54
> Its really weird that it persists if I change these back and forth.

This is definitely unexpected.

If we've ruled out dependency conflict and stale build artifacts, then the only other explanation I can think of right now is that there's indeed a problem in Encore or Timbre, but it requires some specific context (e.g. compiler options and/or versions of other software) to show up.

I'm not so familiar with shadow-cljs though, and completely unfamiliar with luminus - so could be I'm missing something else.

Is it possible that your old project (the one exhibiting) problems is using an older version of shadow-cljs, or ClojureScript? Would it be possible to share the config related to your Cljs build?

I've just pushed `[com.taoensso/encore "3.42.0-timbre364"]` to Clojars. Could you let me know if that reliably works for you? (Should work with any Timbre version).

**Comment by BorisKourt** [comment] 2022-12-07 11:02
Hey, I ran with: 

```clj
   [com.taoensso/timbre "6.0.3" :exclusions [com.taoensso/encore]]
   [com.taoensso/encore "3.42.0-timbre364"]]
```

And it still gives me the error. 

***

I am using the latest version of most libraries (regularly check via [`antiq`](https://github.com/liquidz/antq)), unless there are breaking changes. So I am on latest `shadow-cljs` (which provides the CLJS compiler.)

I will try to see if I can duplicate this project and just strip away everything else. See if its something with the way its configured.

**Comment by ptaoussanis** [comment] 2022-12-07 11:39
Are you by any chance using [clj-kondo](https://github.com/clj-kondo/clj-kondo) in your project that's experiencing the trouble?

**Comment by BorisKourt** [comment] 2022-12-07 12:14
Hey, I have isolated it to just shadow, timbre and encore: https://github.com/BorisKourt/timbre-repro

Hopefully it will be possible to reproduce the error on your end. Steps:

* `npm i`
* `lein uberjar`

I am not sure if you need `shadow-cljs` installed globally or not. 

On my machine that triggers the error every time.

**Comment by ptaoussanis** [comment] 2022-12-07 12:40
Can confirm that I'm seeing the same error with your repo and steps above 👍 
Thanks for the repro! Will investigate and report back.

**Comment by BorisKourt** [comment] 2022-12-07 21:29
Thanks for taking the time on this, really appreciate it! That is quite an unexpected issue. 

Everything appears to be working with `[com.taoensso/encore "3.42.0-timbre364b"]`!

I wonder who this should be passed on to? I can't quite tell if its shadow exposing a clojure bug or just a shadow issue.

**Comment by ptaoussanis** [comment] 2022-12-08 12:56
You're very welcome. Likewise thanks for all the help, and sorry for all your time sunk on this.

`[com.taoensso/encore "3.43.0"]` and `[com.taoensso/timbre "6.0.4"]` are now on Clojars.

I'm inclined not to bother anyone else about this unless the problem recurs.
The issue was clearly either being caused by `enc/defalias` itself, or `defalias` was triggering some underlying cause elsewhere.

If there is an underlying cause, it seems likely that it's triggered only in obscure circumstances. `defalias` is definitely abusing the tooling, so it wouldn't surprise me if it touched an edge-case somewhere.

The current fix/workaround appears to be reliable, so I'm happy to leave it as is for now.

If the problem does recur, I'll dig further into what might actually be going on underneath - either to change the approach, or to ping the relevant upstream folks with clearer info.

Does that sound reasonable to you?

**Comment by BorisKourt** [comment] 2022-12-08 12:57
That sounds totally reasonable. Lets close this one :)

**Closed** 2022-12-08 12:58 UTC
Labels: bug, can close?
