### ISSUE TITLE
cant not log the variables the same time

### ISSUE THREAD

**Issue by vinurs** [ptaoussanis/timbre#352] opened 2022-07-25 16:58 UTC
the code like this
```
(let [user-id 1
        user_id 2]
    (timbre/info user-id user_id))
```
but it outputs
```

  Show: Project-Only All 
  Hide: Clojure Java REPL Tooling Duplicates  (42 frames hidden)

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling src/clj/app/routes/xdm/hulianwang.clj at (21:5)
   #:clojure.error{:phase :compile-syntax-check,
                   :line 21,
                   :column 5,
                   :source
                   "/Users/vinurs/sys-cfg/work/xiaodongmen/xdm-server/src/clj/app/routes/xdm/hulianwang.clj",
                   :symbol fn*}
             Compiler.java: 7119  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 2670  clojure.lang.Compiler$NewExpr$Parser/parse
             Compiler.java: 7111  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 3892  clojure.lang.Compiler$InvokeExpr/parse
             Compiler.java: 7113  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 6124  clojure.lang.Compiler$BodyExpr$Parser/parse
             Compiler.java: 6440  clojure.lang.Compiler$LetExpr$Parser/parse
             Compiler.java: 7111  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 6124  clojure.lang.Compiler$BodyExpr$Parser/parse
             Compiler.java: 5471  clojure.lang.Compiler$FnMethod/parse
             Compiler.java: 4033  clojure.lang.Compiler$FnExpr/parse
             Compiler.java: 7109  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7178  clojure.lang.Compiler/eval
             Compiler.java: 7136  clojure.lang.Compiler/eval
                  core.clj: 3202  clojure.core/eval
                  core.clj: 3198  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1977  clojure.core/with-bindings*
                  core.clj: 1977  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  218  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  217  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  829  java.lang.Thread/run

1. Caused by java.lang.ClassFormatError
   Duplicate field name "user_id" with signature "J" in class file
   app/routes/xdm/hulianwang$eval57944$fn__57945

          ClassLoader.java:   -2  java.lang.ClassLoader/defineClass1
          ClassLoader.java: 1017  java.lang.ClassLoader/defineClass
          ClassLoader.java:  878  java.lang.ClassLoader/defineClass
   DynamicClassLoader.java:   46  clojure.lang.DynamicClassLoader/defineClass
             Compiler.java: 4990  clojure.lang.Compiler$ObjExpr/getCompiledClass
             Compiler.java: 4120  clojure.lang.Compiler$FnExpr/parse
             Compiler.java: 7109  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 2670  clojure.lang.Compiler$NewExpr$Parser/parse
             Compiler.java: 7111  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 3892  clojure.lang.Compiler$InvokeExpr/parse
             Compiler.java: 7113  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 6124  clojure.lang.Compiler$BodyExpr$Parser/parse
             Compiler.java: 6440  clojure.lang.Compiler$LetExpr$Parser/parse
             Compiler.java: 7111  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 6124  clojure.lang.Compiler$BodyExpr$Parser/parse
             Compiler.java: 5471  clojure.lang.Compiler$FnMethod/parse
             Compiler.java: 4033  clojure.lang.Compiler$FnExpr/parse
             Compiler.java: 7109  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7178  clojure.lang.Compiler/eval
             Compiler.java: 7136  clojure.lang.Compiler/eval
                  core.clj: 3202  clojure.core/eval
                  core.clj: 3198  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1977  clojure.core/with-bindings*
                  core.clj: 1977  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  218  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  217  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  829  java.lang.Thread/run


```

**Comment by ptaoussanis** [comment] 2022-07-25 17:23
@vinurs Thanks for the report, this is quite interesting!

Looks like the problem can be reduced to:

```clojure
(let [x- 1 x_ 2]
  (fn [] [x- x_])) ; =>  Duplicate field name "x_" with signature "J" in class file [...]
```

I.e. this doesn't appear to be related to Timbre.

First impression is that this actually looks like it could be a Clojure bug.
I'm not aware of any reason why the above form _should_ throw.

As a first step, I'd suggest trying to see if you can reproduce the above exception on different (esp. earlier) versions of Clojure.

The snippet throws with Clojure 1.11.1, but I haven't checked it yet with any other versions.

**Comment by vinurs** [comment] 2022-07-30 00:26
@ptaoussanis i tested from 1.0.0 to the latest, seems all have the problem
<img width="1195" alt="图片" src="https://user-images.githubusercontent.com/37489300/181862588-2172c829-60a2-4abe-a30d-fe1a44e13553.png">

**Comment by ptaoussanis** [comment] 2022-07-30 07:44
👍 In that case I'd suggest maybe posting this minimal reproducible example to the [Clojure Google Group](https://groups.google.com/g/clojure).

My first guess would be a possible issue with munging somewhere in the Clojure compiler, but someone more knowledgeable on the group should hopefully be able to advise.

**Comment by ptaoussanis** [comment] 2022-09-06 11:35
Closing for now, since this appears to be an upstream Clojure issue/limitation and since there's not much that Timbre could do to work around it afaik.

As a user-level workaround, I guess I could suggest just trying to avoid these kinds of similar binding names. It seems that Clojure is basically munging "-" to "_" which means that the names `x-` and `x_` are treated as identical.

Try use different names if possible - e.g. `user-id-source-1`, `user-id-source-2`, etc.

Hope that's of some help at least, best of luck!

**Closed by ptaoussanis** 2022-09-06 11:35 UTC
Labels: bug?
