### ISSUE TITLE
How to pass timbre log facilities to a library?

### ISSUE THREAD

**Issue by PEZ** [ptaoussanis/timbre#350] opened 2022-03-21 16:57 UTC
Hi there!

Not sure how to phrase this question. I am creating a ClojureScript library and want to give the users of the library a way to plug in some other logger than the default `js/console`.log, et al. So if someone has a logging function that has the same signature as the js/console ones, they can just provide it. But if your favorite logging library is timbre, things get complicated. The closest I have got is:

```clojure
(fn [& msgs] (t/log msgs)
```

Which logs a list and also ”unpacks” things like `js/doument`. 

Direct logging using timbre:

```clojure
(t/debug (repeat 7 {:foo [1 2 3]}) "bar" js/document)
```

Gives:

![image](https://user-images.githubusercontent.com/30010/159315423-f2b826b9-7954-4d01-90f3-93b1f59d5db5.png)

Whereas using the function wrapper, yields:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/30010/159315213-5bedfeed-3d12-4b7c-b98e-bf92dacdb11b.png">

I've gotten some assistance over at Clojurians slack to understand the problem, and it seems what I wanted to provide is simply not possible. But before I give up, I thought I'd should ask you. 😄 

Here's the slack convo: https://clojurians.slack.com/archives/C03S1L9DN/p1647877645650139

**Comment by ptaoussanis** [comment] 2022-03-21 18:25
Hi Peter!

I can't access the linked Slack conversation- but will try to understand from your question as written here.

What I've understood-

- You have a ClojureScript library that creates logging output that may be relevant to your library consumers.
- You'd like to allow your library consumers to control how that logging happens.
- You'd ideally like to do that by allowing library consumers to provide a `(fn [& args]) -> output` fn.
- But you find the output produced by `(fn [& args] (timbre/log args))` unsatisfying.

Is that right so far?

If so, what would your _ideal_ Timbre output look like? The output example you gave for "Direct logging using timbre"? Or that's also not ideal?

Are you familiar with `timbre/log!` and/or the `^:meta {:raw-console? true}` option for the default cljs Timbre console appender? These provide some flexibility that you might find useful. Otherwise let me know exactly what you're looking for and I'll try assist.

Cheers! :-)

**Comment by PEZ** [comment] 2022-03-22 09:35
Cheers!

You've understood things perfectly.

> If so, what would your _ideal_ Timbre output look like? The output example you gave for "Direct logging using timbre"? Or that's also not ideal?

Yes, the timbre logging is ideal. The devs working with the apps consuming my library are big fans of timbre.

Can't say I am familiar with the APIs you mention. I'll have a look at them and will come back with results and/or questions.

Here's a public version of that slack conversation, btw: https://clojurians-log.clojureverse.org/clojurescript/2022-03-21/1647877645.650139

**Comment by ptaoussanis** [comment] 2022-03-22 09:40
> Yes, the timbre logging is ideal. 

Okay, gotcha. That shouldn't be any problem then.

> Can't say I am familiar with the APIs you mention. I'll have a look at them and will come back with results and/or questions.

The `timbre/log!` macro is likely what you want. The relevant difference between `timbre/log` and `timbre/log!` is that the latter takes a single concrete `args` rather than `& args` - that'll help side-step the issue you're having with argument spreading / application.

All of the core Timbre macros are just partials of `timbre/log!`.

**Comment by PEZ** [comment] 2022-03-22 10:52
I fail at making it work.

Trying:

```clojure
(fn [& msgs] (t/log! :debug :p msgs))
```

I get: 

```
Invariant violation in `taoensso.timbre:689`. Test form `([:or nil? sequential?] args)` failed against input val `msgs`.
```

This confuses me, because to me it looks like I am passing a collection. Obviously I am not super savvy with things like this.

And trying to satisfy the spec like so:

```clojure
(fn [& msgs] (t/log! :debug :p [msgs]))
```

Compiles, and logs stuff, but takes me back to square one. 😄 

As for macros/functions. I totally respect that there are tradeoffs and think that the reasons for using timbre often are the extra context it can enrich the output with. It's just my use case that... As the library provider I can only try create some examples helping the consumers, since it is they who will have to wrap the macros. At the library level I can't help them, afaicu, since that would require the library to. depend on timbre, which is what we are trying to avoid in the first place.

**Comment by ptaoussanis** [comment] 2022-03-22 14:03
Apologies, the info I gave you was incorrect. The current implementation actually unintentionally makes a function wrapper needlessly problematic.

> This confuses me, because to me it looks like I am passing a collection.

The `sequential?` check is actually taking place at compile-time. Since `msgs` is a symbol (and not a sequential collection), the assertion is failing.

Have just pushed `[com.taoensso/timbre "5.2.0-SNAPSHOT"]` to [Clojars](https://clojars.org/com.taoensso/timbre/versions/5.2.0-SNAPSHOT).

This should successfully allow `(fn [& msgs] (t/log! :debug :p msgs))` as intended.

If you can confirm, I'll push a stable release.

Again, apologies for the misdirection :-)

**Comment by PEZ** [comment] 2022-03-22 14:56
Thanks! ❤️  This works like a charm. 🎉

**Comment by ptaoussanis** [comment] 2022-03-22 15:28
Great, thanks for the quick confirmation 👍 
`[com.taoensso/timbre "5.2.0"]` is now [on Clojars](https://clojars.org/com.taoensso/timbre).

Closing, but feel free to reopen (or open another issue) if you have any other trouble.

Cheers

**Closed by ptaoussanis** 2022-03-22 15:28 UTC
Labels: question/usage

**Comment by PEZ** [comment] 2022-03-23 05:46
The turnaround time here. Amazing!
