### ISSUE TITLE
View source in generated docs directs to Github 404

### ISSUE THREAD

**Issue by bpringe** [ptaoussanis/timbre#286] opened 2019-05-09 14:44 UTC
When I click view source in the docs for a function, I get a 404 page.

**Comment by ptaoussanis** [comment] 2020-05-06 11:27
Closing as duplicate of https://github.com/ptaoussanis/timbre/issues/264

**Closed by ptaoussanis** 2020-05-06 11:27 UTC
Labels: bug, pull requests welcome

**Comment by bpringe** [comment] 2020-05-06 16:10
My past self must have not been good at checking existing issues first :sweat_smile:
